/* eslint-disable */
/* oxlint-disable */
// Auto-generated by @contentrain/query — do not edit manually
// Re-generate with: npx contentrain-query generate

export type ContentStatus = 'draft' | 'published' | 'in_review' | 'rejected' | 'archived'

export interface CatalogCollection {
  id: string
  featured_products?: string[]
  name: string
  slug: string
  summary?: string
}

export interface FaqItem {
  id: string
  answer: string
  category?: string
  question: string
}

export interface Footer {
  blurb?: string
  columns?: { links?: { href: string; label: string }[]; title: string }[]
  legal_notice?: string
}

export interface Navigation {
  announcement_label?: string
  cta_href?: string
  cta_label?: string
  items?: { emphasis?: boolean; href: string; label: string }[]
}

export interface Product {
  id: string
  badge?: string
  description?: string
  featured?: boolean
  gallery?: string[]
  highlights?: string[]
  image_alt?: string
  image_credit_href?: string
  image_credit_label?: string
  name: string
  price_label: string
  primary_image?: string
  slug: string
  summary: string
}

export interface PromoCampaign {
  id: string
  end_at?: string
  href?: string
  start_at?: string
  summary?: string
  theme?: 'light' | 'dark' | 'accent'
  title: string
}

export interface SeoDefaults {
  canonical_base: string
  meta_description: string
  meta_title: string
  og_image?: string
}

export interface SiteSettings {
  default_locale: string
  og_image?: string
  site_name: string
  site_tagline?: string
  theme_name: string
}

export interface Testimonial {
  id: string
  avatar?: string
  company_name?: string
  person_name: string
  person_role?: string
  quote: string
  rating?: number
}

export interface QueryBuilder<T> {
  locale(lang: string): QueryBuilder<T>
  where<K extends keyof T>(field: K, value: T[K]): QueryBuilder<T>
  sort<K extends keyof T>(field: K, order?: 'asc' | 'desc'): QueryBuilder<T>
  limit(n: number): QueryBuilder<T>
  offset(n: number): QueryBuilder<T>
  include(...fields: string[]): QueryBuilder<T>
  first(): T | undefined
  all(): T[]
}

export interface SingletonAccessor<T> {
  locale(lang: string): SingletonAccessor<T>
  include(...fields: string[]): SingletonAccessor<T>
  get(): T
}

export interface DictionaryAccessor {
  locale(lang: string): DictionaryAccessor
  get(): Record<string, string>
  get(key: string): string | undefined
  get(key: string, params: Record<string, string | number>): string
}

export interface DocumentQuery<T> {
  locale(lang: string): DocumentQuery<T>
  where<K extends keyof T>(field: K, value: T[K]): DocumentQuery<T>
  include(...fields: string[]): DocumentQuery<T>
  bySlug(slug: string): T | undefined
  first(): T | undefined
  all(): T[]
}

export declare function query(model: 'catalog-collection'): QueryBuilder<CatalogCollection>
export declare function query(model: 'faq-item'): QueryBuilder<FaqItem>
export declare function query(model: 'product'): QueryBuilder<Product>
export declare function query(model: 'promo-campaign'): QueryBuilder<PromoCampaign>
export declare function query(model: 'testimonial'): QueryBuilder<Testimonial>
export declare function query(model: string): QueryBuilder<Record<string, unknown>>

export declare function singleton(model: 'footer'): SingletonAccessor<Footer>
export declare function singleton(model: 'navigation'): SingletonAccessor<Navigation>
export declare function singleton(model: 'seo-defaults'): SingletonAccessor<SeoDefaults>
export declare function singleton(model: 'site-settings'): SingletonAccessor<SiteSettings>
export declare function singleton(model: string): SingletonAccessor<Record<string, unknown>>

export declare function dictionary(model: string): DictionaryAccessor

export declare function document(model: string): DocumentQuery<Record<string, unknown>>

export interface ContentrainClient {
  query(model: 'catalog-collection'): QueryBuilder<CatalogCollection>
  query(model: 'faq-item'): QueryBuilder<FaqItem>
  query(model: 'product'): QueryBuilder<Product>
  query(model: 'promo-campaign'): QueryBuilder<PromoCampaign>
  query(model: 'testimonial'): QueryBuilder<Testimonial>
  query(model: string): QueryBuilder<Record<string, unknown>>
  singleton(model: 'footer'): SingletonAccessor<Footer>
  singleton(model: 'navigation'): SingletonAccessor<Navigation>
  singleton(model: 'seo-defaults'): SingletonAccessor<SeoDefaults>
  singleton(model: 'site-settings'): SingletonAccessor<SiteSettings>
  singleton(model: string): SingletonAccessor<Record<string, unknown>>
  dictionary(model: string): DictionaryAccessor
  document(model: string): DocumentQuery<Record<string, unknown>>
}

export declare function createContentrainClient(): ContentrainClient

